### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by DTherHtun** [kovetskiy/zabbixctl#12]
`[dther@opslab zabbixctl]$ zabbixctl -Tp /cache

can't authorize user 'admin' in zabbix server

└─ invalid character '<' looking for beginning of value
`

**Comment by kovetskiy** [comment]
Error happened because zabbixctl expects to see JSON response, but got something that begins with `<` (html, I guess). Please recheck url to zabbix api.

**Comment by DTherHtun** [comment]
Thank You . i need to add  /zabbix/ in url
