### ISSUE TITLE
Can't connect to zabbix

### ISSUE THREAD

**Issue by mbugeia** [kovetskiy/zabbixctl#2]
Hi, I can't manage to connect to my zabbix instance

bin/zabbixctl -Tp /cache  
can't authorize user 'myuser' in zabbix server
└─ invalid character '<' looking for beginning of value

My config file seems correct and contain no  '<'.

**Comment by DantePinky** [comment]
same issue

**Comment by kovetskiy** [comment]
@mbugeia @DantePinky I can help you with your issue when I don't know anything about your case; can you get me more details? also zabbixctl have `--debug` option, it's also can be helpful.

**Comment by mbugeia** [comment]
What details do you want ? I've done the installation and configurations step and try the first example, that's all. I have go v1.6.2 on ubuntu 16.04.

`--debug` doesn't seems to be recognized:
```
bin/zabbixctl --debug -Tp "/cache"
Usage:
  zabbixctl [options] -T [-v]... [-x]... [-d]... [<pattern>]...
  zabbixctl [options] -L [-v]... <pattern>...
  zabbixctl [options] -G [-v]... [<pattern>]...
  zabbixctl [options] -G [-v]... <pattern>... -a <user>
  zabbixctl [options] -G [-v]... <pattern>... -r <user>
  zabbixctl -h | --help
  zabbixctl --version
zsh: exit 1     bin/zabbixctl --debug -Tp "/cache"

```

**Comment by DantePinky** [comment]
yep, zabbixctl haven't  --debug option...

**Comment by kovetskiy** [comment]
ok its -v

**Comment by jiansong** [comment]
I can reproduce this:

```
 ~  zabbixctl -v -L machine /cpu   
[DEBUG] * reading session file
[DEBUG] * session is outdated
[DEBUG] * authorizing
[DEBUG] ~> user.login
[DEBUG] ** user: username
[DEBUG] ** password: **********
[DEBUG] <~ 301 Moved Permanently
can't authorize user 'username' in zabbix server
└─ invalid character '<' looking for beginning of value
```

The reason is I'm using HTTPS, so if I change the setting from

`address = "zabbix.localdomain"`

to 

`address = "https://zabbix.localdomain"`

then it works.

**Comment by otheus** [comment]
I think this issue can be closed, but the docs should clarify that address is essentially a URI. I got stuck on this as well.
