### ISSUE TITLE
parseDate undefined

### ISSUE THREAD

**Issue by tomblich-okta** [kovetskiy/zabbixctl#25]
[~]$ go get github.com/kovetskiy/zabbixctl

# github.com/kovetskiy/zabbixctl
go/src/github.com/kovetskiy/zabbixctl/handle_maintenances.go:584:22: undefined: parseDate
go/src/github.com/kovetskiy/zabbixctl/handle_maintenances.go:594:21: undefined: parseDate
go/src/github.com/kovetskiy/zabbixctl/handle_triggers.go:251:35: undefined: parseDateTime
go/src/github.com/kovetskiy/zabbixctl/handle_triggers.go:253:36: undefined: parseDateTime

**Comment by tomblich-okta** [comment]
go newbie, needed to setup GOPATH and GOROOT

**Comment by tomblich-okta** [comment]
actually I set GOPATH and same issue.  Not sure why handle_maintenance is not finding the parseDate function. 
I'm on go `go version go1.13.1 darwin/amd64`

**Comment by tomblich-okta** [comment]
Did the following:
`cp  parse_date_linux.go parse_date_darwin.go`
`go get github.com/simplereach/timeutils`
`go build`
`go install`

**Comment by kovetskiy** [comment]
Hi! Thanks for the investigation!

**Comment by mjtrangoni** [comment]
@kovetskiy we should change the build line if you want to support Darwin for example. As we do not need to duplicate X times this file
