### ISSUE TITLE
zabbixctl fails to install due to error in handle_latest_data.go lines 105,106

### ISSUE THREAD

**Issue by brocktice** [kovetskiy/zabbixctl#5]
This is with a freshly-installed go version 1.7.1.

[brock@zabbix ~]$ go get github.com/kovetskiy/zabbixctl
# github.com/kovetskiy/zabbixctl
gocode/src/github.com/kovetskiy/zabbixctl/handle_latest_data.go:105: cannot convert nil to type int
gocode/src/github.com/kovetskiy/zabbixctl/handle_latest_data.go:106: cannot use err (type int) as type error in return argument:
	int does not implement error (missing Error method)

**Comment by kovetskiy** [comment]
fixed
