### ISSUE TITLE
event.acknowledge - can't ack

### ISSUE THREAD

**Issue by Najkon** [kovetskiy/zabbixctl#6]
~# zabbixctl -v -Tp -k --only-nack  /high write
[DEBUG] * reading session file
[DEBUG] * using session instead of authorization
[DEBUG] * rewriting session file
:: Requesting information about statuses of triggers
[DEBUG] * retrieving triggers list
[DEBUG] ~> trigger.get
[DEBUG] ** monitored: true
[DEBUG] ** selectHosts: [name]
[DEBUG] ** selectGroups: [groupid name]
[DEBUG] ** sortfield: [lastchange priority]
[DEBUG] ** lastChangeSince: 1474974211
[DEBUG] ** expandData: true
[DEBUG] ** expandDescription: true
[DEBUG] ** skipDependent: true
[DEBUG] ** preservekeys: true
[DEBUG] ** min_severity: 0
[DEBUG] ** withLastEventUnacknowledged: 1
[DEBUG] ** limit: 0
[DEBUG] ** sortorder: DESC
[DEBUG] ** selectLastEvent: extend
[DEBUG] ** selectFunctions: extend
[DEBUG] ** expandExpression: true
[DEBUG] ** filter.value: 1
[DEBUG] <~ 200 OK
[DEBUG] * showing triggers table
[DEBUG] ** searching h.*i.*g.*h.*w.*r.*i.*t.*e
277043085  2016-10-04 11:14:59  WARN  PROBLEM  NACK    disk: high write time (305.5ms)
277052516  2016-10-04 12:57:50  WARN  PROBLEM  NACK    disk: high write time (210.4ms)

:: Proceed with acknowledge? [Y/n]: Y
:: Acknowledging specified triggers
[DEBUG] * acknowledging triggers
[DEBUG] ~> event.acknowledge
[DEBUG] ** eventids: [277043085 277052516]
[DEBUG] <~ 200 OK
can't acknowledge triggers [277043085 277052516]
└─ zabbix returned error while working with api method event.acknowledge
   └─ Invalid params.
      └─ Incorrect arguments passed to function.

**Comment by Najkon** [comment]
and it will be great when to show the hostname of machine e.g.
2016-10-04 12:57:50 WARN PROBLEM NACK - server-k100 - disk: high write time (210.4ms)

**Comment by kovetskiy** [comment]
I guess it is related with Zabbix API compatibility and you have different version then I tested. Now I don't have time to address this issue, but I will be glad to merge pull-request with fixing this troubles.

**Comment by Najkon** [comment]
sorry man, but it's to hard to me for make fixing this troubles. I'm trying but my brain exploded under the pressure of code. It's too bad could be a great tool :)
BTW. I'm using zabbix 3.0

**Comment by kovetskiy** [comment]
@Najkon it's will always hard for you if you doesn't start to try to solve such problems.

**Comment by Najkon** [comment]
@kovetskiy not really is like you say. Belive me, I'm trying but I am in this completely green.. 
I'm looking for something like you have built - not to click trigger each individual on web panel.
